# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'imageCropPicker' do
    pod 'React', :path => '../node_modules/react-native'
    pod 'QBImagePickerController', '3.4.0'
    pod 'RSKImageCropper', '1.5.1'
    pod 'UIImage-Resize', '~> 1.0'
end
