export class Constants {
  static readonly ENCODE_FORMAT: string = 'image/jpeg';
  static readonly ENCODE_QUALITY: number = 100;
  static readonly DOUBLE_NUMBER: number = 2;
  static readonly CLOCK_WISE: number = 90;
  static readonly ANTI_CLOCK: number = -90;
  static readonly IMAGE_FORMAT: string = '.jpg'
  static readonly IMAGE_PREFIX: string = 'image';
  static readonly ENCODE_FILE_PERMISSION: string = 'rw'
}